[build-system]
build-backend = "uv_build"
requires = [ "uv-build>=0.12.2,<0.13" ]

[project]
name = "proxima"
version = "0.0.0"
description = "Add your description here"
readme = "README.md"
authors = [ { name = "Miquel Marin Riera", email = "miquel.marin.riera@gmail.com" } ]
requires-python = ">=3.13"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dependencies = [
  "dotenv>=0.9.9",
  "hishel[httpx]>=1.3.1",
  "httpx>=0.28.1",
  "rich>=15",
  "typer>=0.27.2",
]
scripts.proxima = "proxima.cli:proxima"

[tool.uv]
build-backend.module-name = "proxima"
build-backend.module-root = "src"

[tool.ruff]
target-version = "py313"
line-length = 120
fix-only = true
lint.select = [ "ALL" ]
lint.ignore = [ "COM812", "D203", "D212" ]
lint.isort.force-single-line = true
